### ISSUE TITLE
dropdown goes off-screen

### ISSUE THREAD

**Issue by gluck** [yuanqing/create-figma-plugin#112]
Since I upgraded to latest/v2 (from 1.8.4), dropdown menus are painted off screen when the dropdown is near the top of the page.

Can be reproduced by removing `layout: 'centered'` in storybook (or removing the corresponding class as I do in the GIF below), the first options are no longer visible.

![dropdown](https://user-images.githubusercontent.com/604263/174818654-ec9578ee-7a34-4d3b-8c9a-130d06d9cee2.gif)

**Comment by yuanqing** [comment]
Thanks for reporting. Am able to reproduce this. This seems to happen only when the dropdown has no value set when it is clicked

**Comment by gluck** [comment]
Still getting bad display:
![image](https://user-images.githubusercontent.com/604263/175265095-d41d3d6f-b7aa-4721-8566-3f2412a8b0a1.png)

I'm getting negative values for:
- `maximumTopOffset: -16`
- `minimumTopOffset: -1013`

Then top gets set to `--16px` (which doesn't do anything)

I believe proper values for min/max offsets should be:
```
  const minimumTopOffset = Math.min(
    VIEWPORT_MARGIN,
    rootElementBoundingClientRect.top
  ); // menu should at least be displayed over the dropdown, not below
  const maximumTopOffset = Math.max(
    0,
    rootElementBoundingClientRect.top - VIEWPORT_MARGIN
  ); // menu shouldn't go off screen
```

(should also ensure non-negative, but still sign invert should be done in number, not in string)

**Comment by yuanqing** [comment]
Thanks for testing this! The version I shipped in `2.1.1-alpha.0` doesn’t properly account for `VIEWPORT_MARGIN`. I’ve just managed to figure out the correct algorithm

**Comment by bashmish** [comment]
Since you are working on the fix for this algorithm, maybe good to report another aspect of this issue (let me know if you prefer making a new issue).

When the component is rendered within a container with `overflow: hidden`, which is quite a common case for us due to the need to add scrollbars, we get it clipped too. The reproduction in the storybook might look like this:

![image](https://user-images.githubusercontent.com/137844/177353364-2941c5e3-6672-481e-a83b-3cb308645853.png)

I assume it's because of the usage of a combination of `position: relative` on the dropdown container and `position: absolute` on the dropdown itself.

To support a use-case with `overflow: hidden` container this algorithm might require more refactoring.

**Comment by yuanqing** [comment]
Original bug should be fixed as of `2.1.1` (see [Storybook](https://yuanqing.github.io/create-figma-plugin/storybook/?path=/story/components-dropdown-border--top-left-many-options)). Created a new issue (https://github.com/yuanqing/create-figma-plugin/issues/117) for the bug reported by @bashmish

**Comment by sholzmayer** [comment]
The issue still exists, when you have a separator included and place the menu to the top.
