### ISSUE TITLE
Adding a custom CSS got error

### ISSUE THREAD

**Issue by afnizarnur** [yuanqing/create-figma-plugin#13]
Hi there, 
I got problem when adding a custom CSS to a new fresh init plugin (following the tutorial from [this recipe](https://github.com/yuanqing/create-figma-plugin/blob/master/docs/recipes/ui.md#readme)), I got error:
`Cannot find module './styles.scss' or its corresponding type declarations.`

### How to fix
I don't know if this is the best solution, I can fix it based from [this](https://stackoverflow.com/questions/37548734/tsc-throws-ts2307-cannot-find-module-for-a-local-file), this happens because the default typescript config of create-figma-plugin doesn't include `"moduleResolution": "node"`.

**Comment by yuanqing** [comment]
Hey @afnizarnur! Thanks for reporting. Not able to reproduce the issue as of `0.0.75` – can you check that you are on this version, or do a fresh install if your versions are set to `*`?

**Comment by yuanqing** [comment]
The issue should have been fixed by https://github.com/yuanqing/create-figma-plugin/commit/3d1800a1903734068f6e30ba7fe7876f748e564d

**Comment by weilinzung** [comment]
0.77 has the same error for me. `"moduleResolution": "node",` not fixed for me...

**Comment by weilinzung** [comment]
Also, if scss file has comments like, it will has `CssSyntaxError: You tried to parse SCSS with the standard CSS parser; try again with the postcss-scss parser`. e.g. 
```
// override styles
@import '../lib/figma-plugin-ds/figma-plugin-ds';
```

**Comment by yuanqing** [comment]
Thanks for reporting this @weilinzung! I suspect it could be a tsconfig issue. Can you share a link to a repo that exhibits the issue you’re facing?

**Comment by yuanqing** [comment]
Your tsconfig should look as follows:

```json
{
  "extends": "@create-figma-plugin/tsconfig",
  "compilerOptions": {
    "typeRoots": ["./node_modules/@types", "./node_modules/@figma"]
  }
}
```

**Comment by weilinzung** [comment]
@yuanqing  I just cloned your latest boilerplate.

if any comments between or above of `@import` would cause theCssSyntaxError.


example inside of `ui.tsx`.
```
// override styles
@import '../lib/figma-plugin-ds/figma-plugin-ds';
```

**Comment by yuanqing** [comment]
@weilinzung This issue should be fixed as of `0.0.78`

**Comment by weilinzung** [comment]
@yuanqing it converts all styles to camelcase?

style.scss.d.ts
```
export const colorBox: string;
export const colorText: string;
export const container: string;
export const emptyState: string;
export const inputWrapper: string;
export const layers: string;
export const switchLabel: string;
export const toolWrapper: string;
export const visualBell: string;
export const visualBellSpinnerContainer: string;
```

style.scss
```
.visual_bell {
  position: absolute;
  width: auto;
  bottom: 10px;
  left: 15px;
  right: 15px;
  z-index: 9;

  .visual_bell_spinner_container {
    display: inline-block !important;
  }
}
```

**Comment by yuanqing** [comment]
@weilinzung I made a new issue (https://github.com/yuanqing/create-figma-plugin/issues/16) for this. Would you be keen to submit a PR?

**Comment by weilinzung** [comment]
@yuanqing sure. I would love to.
